namespace ExpenseManagement.Domain.Common;

/// <summary>
/// Base for every persisted aggregate. Ids are sequential GUIDs generated by
/// the database (<c>NEWSEQUENTIALID()</c>) so clustered-index inserts stay
/// append-only, while remaining unguessable enough that an id in a URL is not
/// an enumeration vector.
/// </summary>
public abstract class BaseEntity : IAuditableEntity
{
    public Guid Id { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset? UpdatedAt { get; set; }
}

/// <summary>A <see cref="BaseEntity"/> that is owned by a user and soft-deleted.</summary>
public abstract class UserOwnedEntity : BaseEntity, IUserOwnedEntity, ISoftDeletable
{
    public Guid UserId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTimeOffset? DeletedAt { get; set; }
}
