using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using ExpenseManagement.Application.Common.Interfaces;
using ExpenseManagement.Domain.Entities;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;

namespace ExpenseManagement.Infrastructure.Identity;

/// <summary>
/// Issues and inspects tokens.
///
/// Two rules drive the design:
///
///  * The access token is short-lived and stateless, so a stolen one expires on
///    its own. It carries only what authorisation needs — never an email
///    address beyond the subject claim, never anything the client could not
///    already see.
///  * The refresh token is long-lived, so it is stored hashed. The raw value
///    exists only in the response body and on the device; a dump of the
///    RefreshTokens table yields nothing replayable.
/// </summary>
public class TokenService : ITokenService
{
    private readonly JwtOptions _options;
    private readonly IDateTimeProvider _clock;
    private readonly SigningCredentials _signingCredentials;
    private readonly TokenValidationParameters _validationParameters;

    public TokenService(IOptions<JwtOptions> options, IDateTimeProvider clock)
    {
        _options = options.Value;
        _clock = clock;

        var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_options.Secret));
        _signingCredentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

        _validationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidIssuer = _options.Issuer,
            ValidateAudience = true,
            ValidAudience = _options.Audience,
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = key,

            // Pinning the algorithm closes the "alg: none" and
            // RS256-downgraded-to-HS256 confusion attacks, where a token signed
            // with a different scheme is accepted because the validator infers
            // the algorithm from the attacker-controlled header.
            ValidAlgorithms = [SecurityAlgorithms.HmacSha256],

            // Default is five minutes, which silently extends every token's life.
            ClockSkew = TimeSpan.FromSeconds(30),
        };
    }

    /// <summary>Validation parameters shared with the JWT bearer middleware, so the two cannot drift.</summary>
    public TokenValidationParameters ValidationParameters => _validationParameters;

    public AccessToken CreateAccessToken(ApplicationUser user, IEnumerable<string> roles)
    {
        var now = _clock.UtcNow;
        var expires = now.AddMinutes(_options.AccessTokenMinutes);

        var claims = new List<Claim>
        {
            new(JwtRegisteredClaimNames.Sub, user.Id.ToString()),
            new(JwtRegisteredClaimNames.Email, user.Email ?? string.Empty),
            new(JwtRegisteredClaimNames.Name, user.FullName),

            // A unique id per token, so an individual access token can be
            // denylisted if that ever becomes necessary.
            new(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),

            // Identity's security stamp changes on password change or explicit
            // "sign out everywhere". Carrying it lets the API reject an
            // access token minted before that event without a database lookup.
            new(SecurityStampClaim, user.SecurityStamp ?? string.Empty),
        };

        claims.AddRange(roles.Select(role => new Claim(ClaimTypes.Role, role)));

        var descriptor = new SecurityTokenDescriptor
        {
            Subject = new ClaimsIdentity(claims),
            Issuer = _options.Issuer,
            Audience = _options.Audience,
            IssuedAt = now.UtcDateTime,
            NotBefore = now.UtcDateTime,
            Expires = expires.UtcDateTime,
            SigningCredentials = _signingCredentials,
        };

        var handler = new JsonWebTokenHandler();
        return new AccessToken(handler.CreateToken(descriptor), expires);
    }

    public IssuedRefreshToken CreateRefreshToken(
        Guid userId,
        Guid? familyId,
        string? ipAddress,
        string? userAgent)
    {
        // 256 bits from the OS CSPRNG. Guid.NewGuid() would be tempting and
        // wrong: v4 GUIDs carry only 122 bits and are not generated by a
        // cryptographic RNG on every platform.
        var raw = Convert.ToBase64String(RandomNumberGenerator.GetBytes(32));

        var entity = new RefreshToken
        {
            UserId = userId,
            TokenHash = HashToken(raw),
            FamilyId = familyId ?? Guid.NewGuid(),
            ExpiresAt = _clock.UtcNow.AddDays(_options.RefreshTokenDays),
            CreatedByIp = Truncate(ipAddress, 45),
            UserAgent = Truncate(userAgent, 400),
        };

        return new IssuedRefreshToken(raw, entity);
    }

    /// <summary>
    /// SHA-256, not a password hash.
    ///
    /// A refresh token is 256 bits of uniform randomness, so there is no
    /// dictionary to attack and no work factor to justify — bcrypt here would
    /// only make every refresh call slow. What matters is that the stored form
    /// is not replayable, which a one-way hash already guarantees.
    /// </summary>
    public string HashToken(string rawToken)
    {
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(rawToken));
        return Convert.ToBase64String(bytes);
    }

    public ClaimsPrincipal? GetPrincipalFromExpiredToken(string accessToken)
    {
        var handler = new JsonWebTokenHandler();

        var parameters = _validationParameters.Clone();

        // The whole point of this call is to read an expired token, so lifetime
        // validation is off. Every other check — signature, issuer, audience,
        // algorithm — still runs, so an unsigned or foreign token is rejected.
        parameters.ValidateLifetime = false;

        var result = handler.ValidateTokenAsync(accessToken, parameters)
            .GetAwaiter()
            .GetResult();

        return result.IsValid ? new ClaimsPrincipal(result.ClaimsIdentity) : null;
    }

    /// <summary>Claim type holding Identity's security stamp.</summary>
    public const string SecurityStampClaim = "sstamp";

    private static string? Truncate(string? value, int maxLength) =>
        value is null || value.Length <= maxLength ? value : value[..maxLength];
}
